theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default

locale: en-US
title: pbsladek
name: Paul Baker Sladek
description: pbsladek blog
url: https://pbsladek.github.io
baseurl: /blog
repository: pbsladek/blog
timezone: America/Los_Angeles

search: true
breadcrumbs: false
words_per_minute: 200
read_time: true
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:year/:month/:day/:title/

author:
  name: Paul Baker Sladek
  bio: pbsladek blog
  location: United States
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/pbsladek
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/pbsladek
    - label: X
      icon: fab fa-fw fa-x-twitter
      url: https://x.com/pwbsladek
    - label: npm
      icon: fab fa-fw fa-npm
      url: https://www.npmjs.com/~pbsladek

footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/pbsladek
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/pbsladek

include:
  - _pages

exclude:
  - .bundle
  - .dockerignore
  - .editorconfig
  - .eslintrc
  - .github
  - .gitignore
  - .jekyll-cache
  - .stylelintignore
  - .stylelintrc
  - Dockerfile.dev
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docker-compose.yml
  - docker
  - node_modules
  - package-lock.json
  - package.json
  - tools
  - vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
