theme: jekyll-text-theme

## => Site Settings
##############################
text_skin: default
highlight_theme: default
url     : https://pbsladek.github.io/
baseurl : ""
title   : pbsladek
description: >
  pbsladek blog

## => Language and Timezone
##############################
lang: en
timezone: America/Los_Angeles

## => Author and Social
##############################
author:
  type      : person
  name      : Paul Sladek
  url       : https://pbsladek.github.io/
  avatar    : assets/images/avatar-chess-paul.jpg
  bio: >
    pbsladek blog
  twitter   : pwbsladek
  linkedin  : pbsladek
  github    : pbsladek
  npm       : pbsladek

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: pbsladek/blog
repository_tree: main

## => Paths
##############################
paths:
  root    : "/"
  home    : "/"
  archive : "/archive.html"
  rss     : "/feed.xml"

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0

## TOC
toc:
  selectors: "h1,h2,h3"

## => Markdown Enhancements
##############################
## Mathjax
mathjax: true
mathjax_autoNumber: true

## Mermaid
mermaid: true

## Chart
chart: true

## => Paginate
##############################
paginate: 4
paginate_path: /page:num

## => Sources
##############################
sources: bootcdn

## => Sharing
##############################
sharing:
  provider: false

## => Comments
##############################
comments:
  provider: false

## => Pageview
##############################
pageview:
  provider: false

## => Search
##############################
search:
  provider: default

## => Analytics
##############################
analytics:
  provider: false

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
